# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter:  postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { '5432' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>
  timeout: 5000

db_config: &db_config
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  <<: *db_config

test:
  <<: *default
  <<: *db_config

development:
  <<: *default
  <<: *db_config
